// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DiskInitParameters struct {
	ACL *bool `json:"acl,omitempty" tf:"acl,omitempty"`

	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	Container *string `json:"container,omitempty" tf:"container,omitempty"`

	Mountoptions []MountoptionsInitParameters `json:"mountoptions,omitempty" tf:"mountoptions,omitempty"`

	Mp *string `json:"mp,omitempty" tf:"mp,omitempty"`

	Quota *bool `json:"quota,omitempty" tf:"quota,omitempty"`

	Replicate *bool `json:"replicate,omitempty" tf:"replicate,omitempty"`

	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`

	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	Slot *float64 `json:"slot,omitempty" tf:"slot,omitempty"`

	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`

	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DiskObservation struct {
	ACL *bool `json:"acl,omitempty" tf:"acl,omitempty"`

	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	Container *string `json:"container,omitempty" tf:"container,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Mountoptions []MountoptionsObservation `json:"mountoptions,omitempty" tf:"mountoptions,omitempty"`

	Mp *string `json:"mp,omitempty" tf:"mp,omitempty"`

	Quota *bool `json:"quota,omitempty" tf:"quota,omitempty"`

	Replicate *bool `json:"replicate,omitempty" tf:"replicate,omitempty"`

	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`

	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	Slot *float64 `json:"slot,omitempty" tf:"slot,omitempty"`

	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`

	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DiskParameters struct {

	// +kubebuilder:validation:Optional
	ACL *bool `json:"acl,omitempty" tf:"acl,omitempty"`

	// +kubebuilder:validation:Optional
	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	// +kubebuilder:validation:Optional
	Container *string `json:"container,omitempty" tf:"container,omitempty"`

	// +kubebuilder:validation:Optional
	Mountoptions []MountoptionsParameters `json:"mountoptions,omitempty" tf:"mountoptions,omitempty"`

	// +kubebuilder:validation:Optional
	Mp *string `json:"mp,omitempty" tf:"mp,omitempty"`

	// +kubebuilder:validation:Optional
	Quota *bool `json:"quota,omitempty" tf:"quota,omitempty"`

	// +kubebuilder:validation:Optional
	Replicate *bool `json:"replicate,omitempty" tf:"replicate,omitempty"`

	// +kubebuilder:validation:Optional
	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`

	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// +kubebuilder:validation:Optional
	Slot *float64 `json:"slot,omitempty" tf:"slot,omitempty"`

	// +kubebuilder:validation:Optional
	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`

	// +kubebuilder:validation:Optional
	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type MountoptionsInitParameters struct {
	Noatime *bool `json:"noatime,omitempty" tf:"noatime,omitempty"`

	Nodev *bool `json:"nodev,omitempty" tf:"nodev,omitempty"`

	Noexec *string `json:"noexec,omitempty" tf:"noexec,omitempty"`

	Nosuid *bool `json:"nosuid,omitempty" tf:"nosuid,omitempty"`
}

type MountoptionsObservation struct {
	Noatime *bool `json:"noatime,omitempty" tf:"noatime,omitempty"`

	Nodev *bool `json:"nodev,omitempty" tf:"nodev,omitempty"`

	Noexec *string `json:"noexec,omitempty" tf:"noexec,omitempty"`

	Nosuid *bool `json:"nosuid,omitempty" tf:"nosuid,omitempty"`
}

type MountoptionsParameters struct {

	// +kubebuilder:validation:Optional
	Noatime *bool `json:"noatime,omitempty" tf:"noatime,omitempty"`

	// +kubebuilder:validation:Optional
	Nodev *bool `json:"nodev,omitempty" tf:"nodev,omitempty"`

	// +kubebuilder:validation:Optional
	Noexec *string `json:"noexec,omitempty" tf:"noexec,omitempty"`

	// +kubebuilder:validation:Optional
	Nosuid *bool `json:"nosuid,omitempty" tf:"nosuid,omitempty"`
}

// DiskSpec defines the desired state of Disk
type DiskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DiskParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DiskInitParameters `json:"initProvider,omitempty"`
}

// DiskStatus defines the observed state of Disk.
type DiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DiskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Disk is the Schema for the Disks API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,proxmox}
type Disk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.container) || (has(self.initProvider) && has(self.initProvider.container))",message="spec.forProvider.container is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mp) || (has(self.initProvider) && has(self.initProvider.mp))",message="spec.forProvider.mp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slot) || (has(self.initProvider) && has(self.initProvider.slot))",message="spec.forProvider.slot is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   DiskSpec   `json:"spec"`
	Status DiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskList contains a list of Disks
type DiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Disk `json:"items"`
}

// Repository type metadata.
var (
	Disk_Kind             = "Disk"
	Disk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Disk_Kind}.String()
	Disk_KindAPIVersion   = Disk_Kind + "." + CRDGroupVersion.String()
	Disk_GroupVersionKind = CRDGroupVersion.WithKind(Disk_Kind)
)

func init() {
	SchemeBuilder.Register(&Disk{}, &DiskList{})
}
