apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-proxmox-crossplane
spec:
  controller:
    image: ${REGISTRY_IMAGE}:${VERSION}
  package: ${REGISTRY_IMAGE}:${VERSION}
  ignorePaths:
    - .github
    - examples
    - .gitignore