apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-proxmox-crossplane
spec:
  controller:
    image: ghcr.io/joekky/provider-proxmox-crossplane-controller-amd64:v1.0.0
    args:
      - "--debug"
      - "--terraform-version=1.3.5"
      - "--terraform-provider-source=/terraform.d/plugins/localhost/telmate/proxmox"
      - "--terraform-provider-version=1.0.0"
  ignorePaths:
    - .github
    - examples
    - .gitignore
